service: microservice-go-utilities
#app: microservice-integration-utilities
#tenant: your-tenant-name

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: dev

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  xml2json:
    timeout: '30'
    handler: bin/xml2json
    events:
      - http:
          timeout: '30'
          path: xml2json
          memory: '128'
          method: post